### ISSUE TITLE
部分浏览器导出 PNG 失败

### ISSUE THREAD

**Issue by techird** [fex-team/kityminder#139]
版本 28.0.1500.95 m

**Comment by leson** [comment]
Error: An attempt was made to break through the security policy of the user agent.
    at toDataURL (src/protocol/png.js:114:33)
    at generateDataUrl (src/protocol/png.js:137:31)
    at <async> Promise.callback
    at <async> Promise.invokeCallback
    at <async> Promise.publish
    at <async> Promise.callback

浏览器信息：Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36

**Comment by techird** [comment]
@leson 收到，谢谢！
