### ISSUE TITLE
分享一张脑图后，继续编辑内容并保存，通过分享链接访问到的还是老的内容

### ISSUE THREAD

**Issue by wwbmmm** [fex-team/kityminder#157]

**Comment by techird** [comment]
保存之后，是否出现“分享内容已同步”的提示？

**Comment by wwbmmm** [comment]
出现了“分享内容已同步”的提示，但还是没有更新

**Comment by wwbmmm** [comment]
还有一个问题：
我把这张脑图，取消分享后，再重新分享，生成了一个不一样的url，点击显示找不到文件：

```
Error: 找不到指定的分享文件，分享内容可能已被删除！
    at <Anonymous> (ui/widget/notice.js:147:16)
    at descriptReason (ui/widget/notice.js:178:12)
    at error (ui/menu/share/view.js:44:30)
    at <async> Promise.callback
    at <async> Promise.invokeCallback
    at <async> Promise.publish
    at <async> Promise.callback
```
