### ISSUE TITLE
导出本地PNG图片失败

### ISSUE THREAD

**Issue by maxzhang** [fex-team/kityminder#285]
Error
    at <Anonymous> (ui/widget/notice.js:179:34)
    at getDetail (ui/widget/notice.js:218:24)
    at error (ui/menu/save/download.js:74:26)
    at <async> Promise.callback
    at <async> Promise.invokeCallback
    at <async> Promise.publish
    at <async> Promise.callback

浏览器信息：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36

**Comment by ydleenudt** [comment]
我这边只要导出都会失败，提示
parse error: empty data or data invalid!

**Comment by ydleenudt** [comment]
Chrome+windows7
